version: '3'
services:
  app:
    build: . 
    container_name: django_app
    env_file:
      - .env
    ports:
      - 8000:8000
        #    volumes:
        #- ./dockerized_python/:/app
    depends_on:
      - mysql


  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_03
      MYSQL_DATABASE: app_db
      MYSQL_PASSWORD: root_pass_03
    ports:
      - 3306:3306

